name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test-database:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERID }}
        password: ${{ secrets.DOCKERPASS }}

    - name: Build Database Docker image
      run: docker compose -f docker-compose.yaml build database

    - name: Run Database tests
      run: docker compose -f docker-compose.yaml up --abort-on-container-exit --exit-code-from database

  build-and-test-backend:
    runs-on: ubuntu-latest
    needs: [build-and-test-database]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERID }}
        password: ${{ secrets.DOCKERPASS }}

    - name: Build Backend Docker image
      run: docker compose -f docker-compose.yaml build backend

    - name: Run Backend tests
      run: docker compose -f docker-compose.yaml up --abort-on-container-exit --exit-code-from backend

  deploy-database:
    runs-on: ubuntu-latest
    needs: [build-and-test-database]

    steps:
    - name: Deploy Database
      run: docker compose -f docker-compose.yaml up -d database

  deploy-backend:
    runs-on: ubuntu-latest
    needs: [build-and-test-backend]

    steps:
    - name: Deploy Backend
      run: docker compose -f docker-compose.yaml up -d backend
