name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    services:
      mysqldb:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: ecommerce
        ports:
          - 3307:3306 #3306 is occupied by our original container
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERID }}
        password: ${{ secrets.DOCKERPASS }}

    - name: Build Docker images
      run: docker compose -f docker-compose.yaml build

    - name: Run tests
      run: docker compose -f docker-compose.yaml up -d --abort-on-container-exit --exit-code-from backend

    - name: Cleanup on failure
      if: failure()
      run: docker logs mysqldb

    - name: Push Docker images to Docker Hub
      run: docker compose -f docker-compose.yaml push
