name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQLPASS}}
          MYSQL_DATABASE: ecommerce
          MYSQL_USER: root
          MYSQL_PASSWORD: ${{ secrets.MYSQLPASS}}
        ports:
          - 3306:3306
        options: --name=mysqldb --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERID }}
        password: ${{ secrets.DOCKERPASS }}

    - name: Build Docker images
      run: docker compose -f docker-compose.yml build

    - name: Run tests
      run: docker compose -f docker-compose.yml up --abort-on-container-exit --exit-code-from backend

    - name: Push Docker images to Docker Hub
      run: docker compose -f docker-compose.yml push
